version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
